/**
 * `@omnis/ai-core-types` — the AI Core contract surface.
 *
 * Every other AI Core package depends on this one, and nothing in it depends on a
 * runtime, a transport, a framework or a vendor. It is types plus the small amount of
 * pure logic that defines what those types *mean*: precedence, classification,
 * ordering, plan validation, JSON-safety.
 *
 * The rule for what belongs here: if two packages must agree on it, it lives here. If
 * only one package needs it, it lives there. That is what keeps this module a contract
 * instead of a dumping ground — and what makes a change here a deliberate, reviewable
 * act, since it fans out to every AI Core package at once.
 */

export {
  AI_CORE_CONTRACT_VERSION,
  AI_TELEMETRY_PREFIX,
  DEFAULT_EXECUTION_TIMEOUT_MS,
  DEFAULT_MODEL_TIMEOUT_MS,
  DEFAULT_TOOL_TIMEOUT_MS,
  EMPTY_METADATA,
  MAX_BUDGET_LIMITS,
  MAX_CONTENT_PARTS,
  MAX_EVALUATION_RULES,
  MAX_FALLBACK_CANDIDATES,
  MAX_JSON_SAFE_DEPTH,
  MAX_METADATA_ENTRIES,
  MAX_PLAN_STEPS,
  MAX_POLICY_RULES,
  MAX_REQUEST_MESSAGES,
  MAX_REQUEST_TOOLS,
  MAX_RETRY_ATTEMPTS,
  MAX_STEP_DEPENDENCIES,
  MICRO_USD_PER_USD,
} from "./constants.js";
export type { AiCoreMetadata } from "./constants.js";

export { createAiCoreIdentity } from "./identifiers.js";
export type { AiCoreIdentifier, AiCoreIdentity, AiCoreTenant } from "./identifiers.js";
export {
  createAgentId,
  createBudgetId,
  createCausationId,
  createCorrelationId,
  createEvaluationId,
  createExecutionId,
  createModelId,
  createPlanId,
  createPolicyId,
  createProviderId,
  createReservationId,
  createToolId,
} from "./identifiers.js";
export type {
  AgentId,
  BudgetId,
  CausationId,
  CorrelationId,
  EvaluationId,
  ExecutionId,
  ModelId,
  PlanId,
  PolicyId,
  ProviderId,
  ReservationId,
  SpanId,
  TenantId,
  ToolId,
  TraceId,
} from "./identifiers.js";

export { assertJsonSafe, findJsonSafetyIssue, hasPath, isJsonSafe, readPath } from "./json.js";
export type { JsonSafety } from "./json.js";

export {
  compareModelDescriptors,
  DEFAULT_MODEL_PARAMETERS,
  describeModelReference,
  isModelCapability,
  isModelKind,
  isModelReference,
  isSelectableModelStatus,
  LATENCY_CLASSES,
  MODEL_CAPABILITIES,
  MODEL_KINDS,
  MODEL_STATUSES,
  MODALITIES,
  modelByCapability,
  modelById,
  modelBySlug,
  modelMatchesReference,
  modelSatisfiesCapabilities,
  modelSatisfiesModalities,
} from "./model.js";
export type {
  LatencyClass,
  ModelCapability,
  ModelDescriptor,
  ModelKind,
  ModelModalities,
  ModelParameters,
  ModelPricing,
  ModelReference,
  ModelStatus,
  Modality,
  ResponseFormat,
} from "./model.js";

export {
  compareProviderCandidates,
  compareProviderDescriptors,
  initialProviderHealth,
  isLiveProviderStatus,
  isSelectableProviderStatus,
  PROVIDER_HEALTH_STATES,
  PROVIDER_OPERATIONS,
  PROVIDER_STATUSES,
  providerById,
  providerBySlug,
  TRANSPORT_KINDS,
} from "./provider.js";
export type {
  ProviderAdapter,
  ProviderCandidate,
  ProviderCapabilities,
  ProviderDescriptor,
  ProviderHealth,
  ProviderHealthObservation,
  ProviderHealthState,
  ProviderInvocationContext,
  ProviderInvocationResult,
  ProviderOperation,
  ProviderRateLimit,
  ProviderReference,
  ProviderStatus,
  TransportKind,
} from "./provider.js";

export {
  agentById,
  agentBySlug,
  agentToolBinding,
  agentToolIds,
  AGENT_CAPABILITIES,
  AGENT_KINDS,
  AGENT_MEMORY_KINDS,
  AGENT_STATUSES,
  AGENT_STATES,
  assertAgentDescriptorShape,
  describeAgentReference,
  isActiveAgentState,
  isAgentCapability,
  isExecutableAgentStatus,
  isTerminalAgentState,
  TERMINAL_AGENT_STATES,
  UNCONSTRAINED_AGENT,
} from "./agent.js";
export type {
  AgentCapability,
  AgentDescriptor,
  AgentInstance,
  AgentInstructions,
  AgentKind,
  AgentMemoryKind,
  AgentMemoryReference,
  AgentReference,
  AgentRuntimeConstraints,
  AgentStateName,
  AgentStatus,
  ToolIdList,
} from "./agent.js";

export {
  EMPTY_TOOL_PARAMETER_SCHEMA,
  formatPermission,
  isAtLeastRisk,
  isInvocableToolStatus,
  isToolReference,
  isRetryableSideEffect,
  parsePermission,
  TOOL_DENIAL_REASONS,
  TOOL_KINDS,
  TOOL_PARAMETER_TYPES,
  TOOL_PERMISSION_ACTIONS,
  TOOL_RISK_LEVELS,
  TOOL_RISK_RANK,
  TOOL_SIDE_EFFECTS,
  TOOL_STATUSES,
  toolById,
  toolByName,
  toolParameterSchema,
} from "./tool.js";
export type {
  AgentToolBinding,
  ToolAuditRecord,
  ToolDenialReason,
  ToolDescriptor,
  ToolExecutionEnvironment,
  ToolHandler,
  ToolHandlerResult,
  ToolInvocation,
  ToolKind,
  ToolParameterSchema,
  ToolParameterSpec,
  ToolParameterType,
  ToolPermission,
  ToolPermissionAction,
  ToolReference,
  ToolResult,
  ToolRiskLevel,
  ToolSideEffect,
  ToolStatus,
} from "./tool.js";

export {
  addUsage,
  CONTENT_PART_TYPES,
  createMessage,
  EMPTY_USAGE,
  isIncompleteStopReason,
  MESSAGE_ROLES,
  messageText,
  messageToolCalls,
  MODEL_STREAM_EVENT_TYPES,
  STOP_REASONS,
  textMessage,
} from "./messages.js";
export type {
  AudioContent,
  ContentPart,
  FileContent,
  ImageContent,
  Message,
  MessageRole,
  ModelRequest,
  ModelResponse,
  ModelStreamEvent,
  ModelToolSpec,
  ReasoningContent,
  StopReason,
  StructuredContent,
  TextContent,
  ToolCallContent,
  ToolCallRequest,
  ToolCallResponse,
  ToolResultContent,
  UsageSummary,
} from "./messages.js";

export {
  EXECUTION_KINDS,
  EXECUTION_MODES,
  EXECUTION_PRIORITIES,
  EXECUTION_PRIORITY_RANK,
  EXECUTION_STATUSES,
  findPlanCycle,
  initialExecutionMetadata,
  isPreExecutionStatus,
  isStreamingMode,
  isSuccessExecutionStatus,
  isTerminalExecutionStatus,
  planStepIds,
  isGrantedApproval,
  PRE_EXECUTION_STATUSES,
  TERMINAL_EXECUTION_STATUSES,
  topologicalStepOrder,
  validateExecutionPlan,
} from "./execution.js";
export type {
  ExecutionKind,
  ExecutionMetadata,
  ExecutionMode,
  ExecutionPlan,
  ExecutionPriority,
  ExecutionRequest,
  ExecutionStatus,
  ExecutionStep,
  PlanIssue,
  ExecutionApproval,
} from "./execution.js";

export {
  CONSTRAINT_KINDS,
  describePolicyDecision,
  isBlockingOutcome,
  MATCH_ALL_TARGET,
  mostRestrictiveOutcome,
  numericConstraint,
  listConstraint,
  POLICY_OPERATORS,
  POLICY_OUTCOMES,
  POLICY_PRECEDENCE,
  policyOutcomeRank,
  assertPolicySetSize,
} from "./policy.js";
export type {
  ConstraintKind,
  ConstraintSpec,
  PolicyAction,
  PolicyApprovalRequest,
  PolicyCondition,
  PolicyDecision,
  PolicyEvaluationInput,
  PolicyOperator,
  PolicyOutcome,
  PolicyRule,
  PolicyRuleEvaluation,
  PolicyRuleTarget,
  PolicySet,
} from "./policy.js";

export {
  availableFor,
  BUDGET_CHECK_ALLOWED,
  BUDGET_DIMENSIONS,
  BUDGET_STATUSES,
  BUDGET_WINDOWS,
  budgetHold,
  durationHold,
  findLimit,
  formatMicroUsd,
  holdAmount,
  isBudgetDimension,
  isIntegerAmount,
  isReservableBudgetStatus,
  isReservationActive,
  microUsd,
  RESERVATION_STATES,
  sumHolds,
  toolExecutionHold,
  usageToHolds,
  assertBudgetShape,
} from "./budget.js";
export type {
  Budget,
  BudgetCheckResult,
  BudgetDimension,
  BudgetHold,
  BudgetLimit,
  BudgetReservation,
  BudgetStatus,
  BudgetUsage,
  BudgetWindow,
  ReservationState,
} from "./budget.js";

export {
  assertEvaluationRuleCount,
  assertEvaluationRuleSpec,
  clampScore,
  EVALUATION_DIMENSIONS,
  EVALUATION_VERDICT_RANK,
  EVALUATION_VERDICTS,
  FINDING_SEVERITIES,
  isEvaluationDimension,
  verdictForScore,
  weightedOverallScore,
  worstVerdict,
} from "./evaluation.js";
export type {
  EvaluatedToolResult,
  EvaluationDimension,
  EvaluationFinding,
  EvaluationInput,
  EvaluationResult,
  EvaluationRuleSpec,
  EvaluationScore,
  EvaluationVerdict,
  FindingSeverity,
} from "./evaluation.js";

export {
  adapterContractError,
  approvalRequiredError,
  budgetExhaustedError,
  classifyError,
  createExecutionFailure,
  deadlineExceededError,
  describeFailure,
  duplicateRegistrationError,
  executionCancelledError,
  FAILURE_CLASSES,
  failureFromError,
  illegalAgentTransitionError,
  illegalExecutionTransitionError,
  invalidPlanError,
  isGovernanceFailureClass,
  isRetryableFailureClass,
  isTerminalIntentFailureClass,
  modelNotFoundError,
  noProviderAvailableError,
  permissionDeniedError,
  policyDeniedError,
  providerInvocationError,
  providerNotFoundError,
  providerUnavailableError,
  stepTimeoutError,
  toolExecutionError,
  toolNotFoundError,
} from "./failures.js";
export type {
  ExecutionFailure,
  ExecutionFailureInput,
  FailureClass,
  FailureContext,
  PolicyIdLike,
} from "./failures.js";

export {
  attemptsForStep,
  ATTEMPT_STATUSES,
  executionStatusForResult,
  isExecutionRecordTerminal,
  isSuccessfulResult,
  recordAttemptCount,
  RESULT_STATUSES,
  resultFailure,
  summarizeExecutionRecord,
  totalRecordUsage,
  withExecutionTiming,
  withGovernanceOutcome,
} from "./results.js";
export type {
  AttemptStatus,
  ExecutionAttempt,
  ExecutionOutcomeInput,
  ExecutionRecord,
  ExecutionResult,
  ExecutionTimelineEntry,
  ResultStatus,
} from "./results.js";
export { isAiCoreSlug, SLUG_CONTRACT, SLUG_PATTERN } from "./slugPattern.js";
